# Generated by Django 3.0.4 on 2020-03-04 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200304_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='achievement',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.Habit'),
        ),
        migrations.AddField(
            model_name='record',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
    ]
