# Generated by Django 3.0.4 on 2020-03-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200304_1457'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('date', 'habit', 'owner'), name='unique_record'),
        ),
    ]
