# Generated by Django 3.0.4 on 2020-03-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200304_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date']},
        ),
    ]
