# Generated by Django 3.0.4 on 2020-03-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200304_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date']},
        ),
    ]
