# Generated by Django 3.0.4 on 2020-03-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200305_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(help_text='What action are you performing for this habit?', max_length=64),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.PositiveIntegerField(help_text='How much you want accomplish daily'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(help_text='The name of your new habit', max_length=64),
        ),
        migrations.AlterField(
            model_name='habit',
            name='units',
            field=models.CharField(default='times', help_text='The units/how many times you want to do your habit daily', max_length=64),
        ),
    ]
