# Generated by Django 3.0.4 on 2020-03-07 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20200306_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observer',
            name='habit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='core.Habit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observer',
            name='observer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='habit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.Habit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='observer',
            constraint=models.UniqueConstraint(fields=('observer', 'habit'), name='unique_observers'),
        ),
    ]
